name: Assign User to Cognito Group

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'The email address of the user to promote'
        required: true
      group:
        description: 'The Cognito group to assign (e.g., ANALYST or ADMIN)'
        required: true
        default: 'ANALYST'

jobs:
  assign-role:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Add User to Group
        run: |
          aws cognito-idp admin-add-user-to-group \
            --user-pool-id us-east-1_22ZpQp5MB \
            --username "${{ github.event.inputs.email }}" \
            --group-name "${{ github.event.inputs.group }}"
          
          echo "Successfully assigned ${{ github.event.inputs.email }} to the ${{ github.event.inputs.group }} group!"
